title: Araiza's Photography
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
permalink: ':title/'
baseurl: "/araizas-photography" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: Araiza's Photography # add your name
author-pic: adam-face.jpg
about-author: My name is Nora Garcia. I’m a full-time traveler blogger and photographer who’s been exploring the world for over 2 years.

# Contact links
email: araizasphotography@gmail.com
phone: +1 619-805-5530
website: # Add your website, do not add http://
linkedin: # Add your Linkedin handle
github: # Add your Github handle
twitter: # Add your Twitter handle
facebook: https://www.facebook.com/Araizasphotography/
instagram: # Add your Instagram handle
pinterest: # Add your Pinterest handle

# Newsletter
mailchimp: # Add your MailChimp form identifier.

# Disqus
discus_identifier: mr-brown # Add your discus identifier

# Tracker
analytics: # Google Analytics

# Paginate
paginate: 6
paginate_path: /page:num/

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "package-lock.json", "assets/css/sass/"]
